[package]
name = "ping-pong"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anysystem = { path = "../.." }
assertables = "3.2.2"
clap = { version = "4", features = ["cargo", "derive"] }
env_logger = "0.11"
log = "0.4"
sugars = "3"
